### ISSUE TITLE
index.html isn't generated in public

### ISSUE THREAD

**Issue by janat08** [OffGridNetworks/fuse-box-create-react-app#4]
generic create script produces no index.html

**Comment by guybarnard** [comment]
Check `src/` folder and see if it's there?  This is currently a difference from the base create-react-app scripts in that index.html and index.js are co-located.   

Noticing that the readme indicates it should be in `public` so this is still an open issue that will need to be resolved.  Let me know in meantime if you're seeing it in `src/`

**Comment by janat08** [comment]
it is, but the documentaiton says it must be otherwise (as in somewhere it demands it). Anyway I can't start it on windows.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\Users\user\dev\fuse-prod0
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 verbose node v8.11.3
9 verbose npm  v5.6.0
10 error missing script: build
11 verbose exit [ 1, true ]

```

**Comment by janat08** [comment]
Same issue for this repo: https://github.com/fullstackreact/food-lookup-demo
Asks you to run npm build which doesn't exist.

**Comment by janat08** [comment]
although the build script exists in generated project.

**Comment by janat08** [comment]
Sorry the wrong log above:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fuse-prod@0.1.0~prestart: fuse-prod@0.1.0
6 info lifecycle fuse-prod@0.1.0~start: fuse-prod@0.1.0
7 verbose lifecycle fuse-prod@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fuse-prod@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user\dev\fuse-prod\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\PostgreSQL\pg10\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\user\AppData\Local\hyper\app-2.0.0\resources\bin;C:\Users\user\AppData\Roaming\npm;C:\Users\user\dev\apps;C:\Program Files\MongoDB\Server\4.0\bin;C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin
9 verbose lifecycle fuse-prod@0.1.0~start: CWD: C:\Users\user\dev\fuse-prod
10 silly lifecycle fuse-prod@0.1.0~start: Args: [ '/d /s /c', 'fuse-box-react-scripts start' ]
11 silly lifecycle fuse-prod@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle fuse-prod@0.1.0~start: Failed to exec start script
13 verbose stack Error: fuse-prod@0.1.0 start: `fuse-box-react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid fuse-prod@0.1.0
15 verbose cwd C:\Users\user\dev\fuse-prod
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error fuse-prod@0.1.0 start: `fuse-box-react-scripts start`
22 error Exit status 1
23 error Failed at the fuse-prod@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by janat08** [comment]
errors in consoles:
```
Error: [BABEL] unknown: The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators (While processing: "C:\\Users\\user\\dev\\fuse-prod\\node_modules\\@babel\\plugin-proposal-decorators\\lib\\index.js")
    at _default (C:\Users\user\dev\fuse-prod\node_modules\@babel\plugin-proposal-decorators\lib\index.js:46:11)
    at C:\Users\user\dev\fuse-prod\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at loadDescriptor (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\full.js:157:14)
    at cachedFunction (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\caching.js:32:19)
    at loadPluginDescriptor (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\full.js:192:28)
    at config.plugins.map.descriptor (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\config\full.js:100:6)
    at transformSync (C:\Users\user\dev\fuse-prod\node_modules\@babel\core\lib\transform.js:41:38)
```
